# for local development
# running from base directory: docker-compose -f deploy/docker-compose.yml -p project1 up --build
version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile

    ports:
      - "8080:8080"

    command: ./src/img_convert


